config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
    get "/" => "welcome#index"
  end


  get '/average_data' => "shang_hai_restaurant#average_data"
  get '/total_data' => "shang_hai_restaurant#total_data"

  root "shang_hai_restaurant#average"
  get '/average' => "shang_hai_restaurant#average"
  get '/total' => "shang_hai_restaurant#total"
  namespace :admin do
    # sidekiq monitors
    require 'sidekiq/web'
    Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      # Protect against timing attacks: (https://codahale.com/a-lesson-in-timing-attacks/)
      # - Use & (do not use &&) so that it doesn't short circuit.
      # - Use `variable_size_secure_compare` to stop length information leaking
      ActiveSupport::SecurityUtils.variable_size_secure_compare(username, 'admin') &
          ActiveSupport::SecurityUtils.variable_size_secure_compare(password, 'sidekiq_admin')
    end
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/redis/decision_trees.rb
require 'csv'
class Redis::DecisionTrees
  REDIS_TIME_OUT = 4
  STATE = {
      :success => "Success",
      :training => "Training",
      :failed => "Failed"
  }.freeze

  def self.find(id)
    keys = $redis.keys.grep(/#{id}.*/).map {|item| item.gsub("#{@id}_", "")}
    Rails.logger.info("Select Redis::DecisionTrees WHERE id  = #{id}")
    if keys.blank?
      return {}
    else
      return Redis::DecisionTrees.new(id)
    end
  end

  def schedule_auto_save_job
    DecisionTreeExpireWorker.cancel!(self.auto_save_jid)
    self.auto_save_jid = DecisionTreeExpireWorker.perform_in((REDIS_TIME_OUT.hour - 5.minutes), id)
    Rails.logger.info("New job_id #{self.auto_save_jid}")
  end


  def method_missing(method_name, *args, &blk)
    match = method_name.to_s.match(/(.*?)([=]?)$/)
    case match[2]
      when "="
        $redis.set("#{@id}_#{match[1]}", {:data => args[0]}.to_json)
        $redis.expire("#{@id}_#{match[1]}", REDIS_TIME_OUT.hour.to_i)
      else
        (JSON.parse($redis.get("#{@id}_#{match[1]}")) rescue {})["data"]
    end
  end

  def error_message
    error_message = $redis.get("#{@id}_error_message")
    $redis.del("#{@id}_error_message")
    error_message
  end


  def save_data(data)
    self.validate_result = (data["data"]["validate_result"].to_f * 100).round(3).to_s + "%"
    self.tree_structure = data["data"]["hash_form_tree_struct"]
    self.node_data = data["data"]["node_data"]
    self.divide_leaf_by_level(data["data"])

    # self.feat_names ||= data["data"]["feat_names"]
    time_consumption = data["data"]["time_consumption"].to_f
    self.time_consumption = Time.at(time_consumption).utc.strftime("%H:%M:%S")

  end

  def update(data)
    self.save_data(data)
  end

  def update_attributes(attributes)
    return if attributes.blank?
    new_attributes = attributes.stringify_keys
    new_attributes.each do |k, v|
      self.send("#{k}=", v)
    end
  end

  def delete
    if self.auto_save_jid
      DecisionTreeExpireWorker.cancel!(self.auto_save_jid)
    end
    attr_keys = $redis.keys.grep(/#{@id}.*/)
    attr_keys.each {|key| $redis.del(key)}
  end

  def attributes
    $redis.keys.grep(/#{@id}.*/).map {|item| item.gsub("#{@id}_", "")}
  end

  def initialize(id, data = nil)
    @id = id.to_i
    self.id = id.to_i
    if data.present?
      self.save_data(data)
    end
  end

  def update_key_expire_time
    Rails.logger.info("Reset key expire time of clt_tree: #{@id}")
    keys = $redis.keys.grep(/#{@id}.*/)
    keys.each {|key|
      $redis.expire(key, REDIS_TIME_OUT.hour.to_i)
    }
  end

end

app/models/restaurant_datum.rb
class RestaurantDatum < ApplicationRecord

  def self.avg_to_json
    [self.all.map {
        |r| {name: r.name, value: [r.longitude.to_f, r.latitude.to_f, r.price.to_f]}
    }, self.all.maximum(:price)]
  end

  def self.total_to_json
    [self.all.map {
        |r| {name: r.name, value: [r.longitude.to_f, r.latitude.to_f, r.price.to_f * r.review_cnt]}
    }, self.all.maximum("price * review_cnt")]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def is_admin?
    is_admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/shang_hai_restaurant_controller.rb
class ShangHaiRestaurantController < ApplicationController
  layout 'echart'
  STYLE = "mapbox://styles/sandersaaa/cjficjvvld53d2qrq6o5q986n"
  COLOR = ["#4A3F6A", "#55487A", "#5B4C82", "#825E89", "#91678C", "#9E6F8F", "#B98196", "#D1929C", "#F4AFA6", "#F5C6A0", "#F5D29A", "#F4DC93", "#F4E48C", "#F4E986"]

  def average
    @map_style_path = STYLE
    @color_range = COLOR
    @pitch = params[:pitch] || 60
  end

  def total
    @map_style_path = STYLE
    # @color_range = ["#F4E986", "#F4E48C", "#F4DC93", "#F5D29A", "#F5C6A0", "#F4AFA6", "#D1929C", "#B98196", "#9E6F8F", "#91678C", "#825E89", "#5B4C82", "#55487A", "#4A3F6A"]
    @color_range = COLOR
    @pitch = params[:pitch] || 60
  end

  def average_data
    data = RestaurantDatum.avg_to_json
    render :json => data
  end


  def total_data
    data = RestaurantDatum.total_to_json
    render :json => data
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @text = Time.now.to_s + "SHAME"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning" 
  end
end

app/helpers/shang_hai_restaurant_helper.rb
module ShangHaiRestaurantHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_echart_footer.html.erb
<%= content_for :handwrite_javascript do %>
  <script type="text/javascript">
      $(
          function () {
              function footerPosition() {
                  $("footer").removeClass("fixed-bottom");
                  var contentHeight = document.body.scrollHeight,
                      winHeight = window.innerHeight;
                  if (!(contentHeight > winHeight)) {
                      $("footer").addClass("fixed-bottom");
                  } else {
                      $("footer").removeClass("fixed-bottom");
                  }
              }

              footerPosition();
              $(window).resize(footerPosition);
          }
      )
  </script>

<% end %>

<footer class="container fixed-bottom" style="margin-top: 100px;">
  <p class="text-center">Copyright © <%= "#{Time.now.year}" %>
    <br>Design by: <a href="#">向晨, 鲍壹方, 邓梦莹, 郭盼盼</a>
  </p>
</footer>

app/views/common/_flashes.html.erb
<% if flash.any? %>
<% user_facing_flashes.each do |key,value| %>
<div class="alert alert-dismissable alert-<%= flash_class(key)%>">
	<button class="close" data-dismiss="alert">×</button>
	<%= value %>
</div>
<% end %>
<% end %>

app/views/common/_footer.html.erb
<%= content_for :handwrite_javascript do %>
  <script type="text/javascript">
      $(
          function () {
              function footerPosition() {
                  $("footer").removeClass("fixed-bottom");
                  var contentHeight = document.body.scrollHeight,
                      winHeight = window.innerHeight;
                  if (!(contentHeight > winHeight)) {
                      $("footer").addClass("fixed-bottom");
                  } else {
                      $("footer").removeClass("fixed-bottom");
                  }
              }

              footerPosition();
              $(window).resize(footerPosition);
          }
      )
  </script>

<% end %>

<footer class="container fixed-bottom" style="margin-top: 100px;">
  <p class="text-center">Copyright © <%= "2017 - #{Time.now.year}" %>
    <br>Design by
    <a href="https://shaheming.github.io/" target=_new>Heming Sha</a>
  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Heming's Website</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
            <% if !current_user %>
                <li><%= link_to("注册",new_user_registration_path) %></li>
                <li><%= link_to("登录",new_user_session_path) %></li>
                <% else %>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                     Hi!, <%= current_user.email %>
                     <b class="caret"></b>
                     </a>
                     <ul class="dropdown-menu">
                     <% if current_user.is_admin? %>
                      <li><%= link_to("Admin Panel",admin_path) %></li> 
                     <% end %>
                         <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
                     </ul>
                </li>
            <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Heming Sha</title>
		<%= csrf_meta_tags %>
		<%= stylesheet_link_tag 'application' %>
		
	</head>
	<body>
		<div class="container-fluid">
			<%= render "common/navbar" %>
			<%= render "common/flashes" %>
			<div class="row">
				<div class="col-md-2">
					<%= link_to("Admin",admin_path,class:"btn btn-info") %>
					<br>
					<br>
					<%= link_to("Wechat Images",admin_wechat_index_path,class:"btn btn-info") %>
				</div>
				<div class="col-md-10">
					<%= yield %>
				</div>
			</div>
		</div>
		
		<%= render "common/footer" %>
		<%= javascript_include_tag 'application' %>
		<%= yield :handwrite_javascript %>
	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Heming Sha</title>
		<%= csrf_meta_tags %>
		<%= stylesheet_link_tag 'application' %>
		<%= javascript_include_tag 'application' %>
	</head>
	<body>
		<div class="container-fluid">
			<%= render "common/navbar" %>
			<%= render "common/flashes" %>
			<%= yield %>
		</div>
		
		<%= render "common/footer" %>

		<%= yield :handwrite_javascript %>
	</body>
</html>

app/views/layouts/echart.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShangHai Restaurant</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
</head>
<body>
<div class="container-fluid">
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Shang Hai Restaurant Visualization</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to("Average", average_url) %></li>
          <li><%= link_to("Total", total_url) %></li>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
  </nav>
  <main>
    <%= yield %></main>
</div>
<%= render "common/echart_footer" %>
<%= yield :handwrite_javascript %>
</body>
</html>

app/views/shang_hai_restaurant/average.html.erb
<div id="main" style="height: 100%;width: 100%;border:1px solid #ccc;padding:10px;"></div>
<script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/echarts/echarts-all-3.js"></script>
<script src="js/echarts.min.js"></script>
<script src="js/echarts-gl.js"></script>
<script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.39.1/mapbox-gl.js'></script>
<link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.39.1/mapbox-gl.css' rel='stylesheet'/>
<script type="text/javascript">
    var uploadedDataURL = "average_data";
    mapboxgl.accessToken = "pk.eyJ1Ijoic2FuZGVyc2FhYSIsImEiOiJjamZmZG84d28ydmNuMnlvYmd2azVpMG9sIn0.VMXdPrekGQ6kxA9Rwk76Sg";
    var myChart = echarts.init(document.getElementById('main'));
    myChart.showLoading();
    $.getJSON(uploadedDataURL, function (linedata) {

        myChart.hideLoading();

        myChart.setOption({
            // http://echarts.baidu.com/option.html#visualMap-continuous
            tooltip: {
                trigger: 'item',
                formatter: function (value) {
                    var data = value["data"];
                    var name = data["name"];
                    var price = data["value"][2]
                    return `店名：${name} <br> 平均消费金额：￥${price.toLocaleString()}`; // 范围标签显示内容。
                }
            },

            visualMap: {
                show: false,
                calculable: true,
                realtime: false,
                inRange: {
                    color:<%= raw @color_range %>
                },
                outOfRange: {
                    colorAlpha: 0
                },
                max: linedata[1]
            },
            mapbox: {
                center: [121.4693, 31.123070],
                zoom: 11.5,
                pitch: <%= @pitch %>,
                bearing: -10,
                style: '<%= @map_style_path %>',
                boxHeight: 50,
                // altitudeScale: 3e2,
                postEffect: {
                    enable: true,
                    SSAO: {
                        enable: true,
                        radius: 2,
                        intensity: 1.5
                    }
                },
                light: {
                    main: {
                        intensity: 1,
                        shadow: true,
                        shadowQuality: 'high'
                    },
                    ambient: {
                        intensity: 0.
                    },
                    ambientCubemap: {
                        texture: '',
                        exposure: 1,
                        diffuseIntensity: 0.5
                    }
                }
            },
            series: [{
                type: 'bar3D',
                shading: 'realistic',
                coordinateSystem: 'mapbox',
                barSize: 0.2,
                bevelSize: 0.3,
                // silent: true,
                data: linedata[0],
                barSmoothness: 100,
                itemStyle: {
                    emphasis: {label: {show: false}}
                }

            }]
        });
    });

</script>

app/views/shang_hai_restaurant/total.html.erb
<div id="main" style="height: 100%;width: 100%;border:1px solid #ccc;padding:10px;"></div>
<script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/echarts/echarts-all-3.js"></script>
<script src="js/echarts.min.js"></script>
<script src="js/echarts-gl.js"></script>
<script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.39.1/mapbox-gl.js'></script>
<link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.39.1/mapbox-gl.css' rel='stylesheet'/>
<br>
<script type="text/javascript">
    var uploadedDataURL = "total_data";
    mapboxgl.accessToken = "pk.eyJ1Ijoic2FuZGVyc2FhYSIsImEiOiJjamZmZG84d28ydmNuMnlvYmd2azVpMG9sIn0.VMXdPrekGQ6kxA9Rwk76Sg";
    var myChart = echarts.init(document.getElementById('main'));
    myChart.showLoading();
    $.getJSON(uploadedDataURL, function (linedata) {

        myChart.hideLoading();

        myChart.setOption({
            // http://echarts.baidu.com/option.html#visualMap-continuous
            tooltip: {
                trigger: 'item',
                formatter: function (value) {
                    var data = value["data"];
                    var name = data["name"];
                    var price = data["value"][2]
                    return `店名：${name} <br> 消费总额：￥${price.toLocaleString()}`; // 范围标签显示内容。
                }
            },
            visualMap: {
                show: false,
                calculable: true,
                realtime: false,
                inRange: {
                    color:<%= raw @color_range%>
                },
                outOfRange: {
                    colorAlpha: 0
                }
                ,
                max: linedata[1]
            },
            mapbox: {
                center: [121.4693, 31.123070],
                zoom: 11.5,
                // pitch: 60,
                pitch: <%= @pitch %>,
                bearing: -10,
                style: '<%= @map_style_path %>',
                boxHeight: 50,
                // altitudeScale: 3e2,
                postEffect:
                    {
                        enable: true,
                        SSAO:
                            {
                                enable: true,
                                radius:
                                    2,
                                intensity:
                                    1.5
                            }
                    }
                ,
                // light: {
                //     main: {
                //         intensity: 1,
                //         shadow:
                //             true,
                //         shadowQuality:
                //             'high'
                //     }
                //     ,
                //     ambient: {
                //         intensity: 0.
                //     }
                //     ,
                //     ambientCubemap: {
                //         texture: '',
                //         exposure:
                //             1,
                //         diffuseIntensity:
                //             0.5
                //     }
                // }
            }
            ,
            series: [{
                type: 'bar3D',
                shading: 'realistic',
                coordinateSystem: 'mapbox',
                barSize: 0.2,
                bevelSize: 0.2,
                // silent: true,
                data: linedata[0],
                barSmoothness: 100,
                itemStyle: {
                    emphasis: {label: {show: false}},
                    // opacity:0.9
                }
            }]
        })
        ;
    });

</script>

app/views/welcome/index.html.erb
<div id="main" style="height:500px;border:1px solid #ccc;padding:10px;"></div>
<div id="mainMap" style="height:500px;border:1px solid #ccc;padding:10px;"></div>

<!--Step:2 Import echarts.js-->
<!--Step:2 引入echarts.js-->
<script src="js/echarts-all.js"></script>

<script type="text/javascript">
    // Step:3 echarts & zrender as a Global Interface by the echarts-plain.js.
    // Step:3 echarts和zrender被echarts-plain.js写入为全局接口
    (function () {
            console.log('init_echarts');
        }
    )();
    var myChart = echarts.init(document.getElementById('main'));
    myChart.setOption({
        tooltip: {
            trigger: 'axis'
        },
        legend: {
            data: ['蒸发量', '降水量']
        },
        toolbox: {
            show: true,
            feature: {
                mark: {show: true},
                dataView: {show: true, readOnly: false},
                magicType: {show: true, type: ['line', 'bar']},
                restore: {show: true},
                saveAsImage: {show: true}
            }
        },
        calculable: true,
        xAxis: [
            {
                type: 'category',
                data: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月']
            }
        ],
        yAxis: [
            {
                type: 'value',
                splitArea: {show: true}
            }
        ],
        series: [
            {
                name: '蒸发量',
                type: 'bar',
                data: [2.0, 4.9, 7.0, 23.2, 25.6, 76.7, 135.6, 162.2, 32.6, 20.0, 6.4, 3.3]
            },
            {
                name: '降水量',
                type: 'bar',
                data: [2.6, 5.9, 9.0, 26.4, 28.7, 70.7, 175.6, 182.2, 48.7, 18.8, 6.0, 2.3]
            }
        ]
    });

    // --- 地图 ---
    var myChart2 = echarts.init(document.getElementById('mainMap'));
    myChart2.setOption({
        tooltip: {
            trigger: 'item',
            formatter: '{b}'
        },
        series: [
            {
                name: '中国',
                type: 'map',
                mapType: 'china',
                selectedMode: 'multiple',
                itemStyle: {
                    normal: {label: {show: true}},
                    emphasis: {label: {show: true}}
                },
                data: [
                    {name: '广东', selected: true}
                ]
            }
        ]
    });
</script>

app/views/welcome/test.html.erb
<div id="main" style="height:500px;border:1px solid #ccc;padding:10px;"></div>
<!--<script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/echarts/echarts-all-3.js"></script>-->

<!--<script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/echarts/echarts-all-3.js"></script>-->

<script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/echarts/echarts-all-3.js"></script>
<!--<script src="js/echarts-all.js"></script>-->
<script src="js/echarts.min.js"></script>
<script src="js/echarts-gl.js"></script>
<!--<script src="js/EchartsLayer.js"></script>-->


<script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.39.1/mapbox-gl.js'></script>
<link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.39.1/mapbox-gl.css' rel='stylesheet' />
<script type="text/javascript">
    var uploadedDataURL = "restaurant_data";

    mapboxgl.accessToken = "pk.eyJ1Ijoic2FuZGVyc2FhYSIsImEiOiJjamZmZG84d28ydmNuMnlvYmd2azVpMG9sIn0.VMXdPrekGQ6kxA9Rwk76Sg";
    var myChart = echarts.init(document.getElementById('main'));
    myChart.showLoading();
    var linedata = [1000,1000]
    $.getJSON(uploadedDataURL, function (linedata) {

        myChart.hideLoading();

        myChart.setOption({

            visualMap: {
                show: false,
                calculable: true,
                realtime: false,
                inRange: {
                    color: ['#313695', '#4575b4', '#74add1', '#abd9e9', '#e0f3f8', '#ffffbf', '#fee090', '#fdae61', '#f46d43', '#d73027',
                        '#a50026']
                },
                outOfRange: {
                    colorAlpha: 0
                },
                max: linedata[1]
            },
            mapbox: {
                center: [121.4693, 31.123070],
                zoom: 10,
                pitch: 50,
                bearing: -10,
                style: 'mapbox://styles/mapbox/light-v9',
                boxHeight: 50,
                // altitudeScale: 3e2,
                postEffect: {
                    enable: true,
                    SSAO: {
                        enable: true,
                        radius: 2,
                        intensity: 1.5
                    }
                },
                light: {
                    main: {
                        intensity: 1,
                        shadow: true,
                        shadowQuality: 'high'
                    },
                    ambient: {
                        intensity: 0.
                    },
                    ambientCubemap: {
                        texture: 'assets/map.jpg',
                        exposure: 1,
                        diffuseIntensity: 0.5
                    }
                }
            },
            series: [{
                type: 'bar3D',
                shading: 'realistic',
                coordinateSystem: 'mapbox',
                barSize: 0.2,
                silent: true,
                data: linedata[0]
            }]
        });
    });

</script>